// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqhlwpnuxkxkvuuheean.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxaGx3cG51eGt4a3Z1dWhlZWFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTY2MzYsImV4cCI6MjA2OTk3MjYzNn0.E3KVuVIO5XLFwzTcfqUa_XmkMki72o8ZaASo8QiXib8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});